#!/bin/bash
if [ -f "Makefile" ]; then
    CMD="make test-plone3"
elif [ -f "bin/test" ]; then
    CMD="bin/test"
fi
if [ ! -z "$CMD" ]; then
    $CMD
    RESULT=$?
    if [ $RESULT -ne 0 ]; then
        echo "failed $CMD"
        exit 1
    fi
fi
exit 0
