#!/bin/bash
if [ -f "Makefile" ]; then
    makelist=$(make -qp | awk -F':' '/^[a-zA-Z0-9][^$#\/\t=]*:([^=]|$)/ {split($1,A,/ /);for(i in A)print A[i]}')
    for maketest in "test-plone3" "test"
    do
        if [ $(echo "$makelist" | grep -x "$maketest") ];then
            CMD="make $maketest"
            break
        fi
    done
elif [ -f "bin/test" ]; then
    CMD="bin/test"
elif [ -d "../../devel" ]; then
    if [ -f "../../bin/test-all" ]; then
        CURRENT=`pwd`
        BASENAME=`basename "$CURRENT"`
        CMD="../../bin/test-all --package=$BASENAME"
    fi
fi

if [ ! -z "$CMD" ]; then
    $CMD
    RESULT=$?
    if [ $RESULT -ne 0 ]; then
        echo "failed $CMD"
        exit 1
    fi
fi
exit 0
